algoritmo "contageminteligente"
var
   in, fim: inteiro
inicio
   Escreval ("CONTAGEM INTELIGENTE")
   Escreval ("--------------------")
   Escreva ("Início: ")
   Leia (in)
   Escreva ("Fim: ")
   Leia (fim)
   Escreval ("--------------------")
   Escreval (" C O N T A N D O ")
   Escreval ("--------------------")

    Enquanto (in < fim) faca
         in <- in + 1
         Escreva (in,"..")
      FimEnquanto
fimalgoritmo