algoritmo "referencia"
var
   x, y: inteiro
   Procedimento soma (var A, B: inteiro)
     inicio
        A<- A + 1
        B<- B + 2
        Escreval ("O valor de A: ", A)
        Escreval ("O valor de B: ", B)
        Escreval("A soma de A+ B é: ", A+B)
   FimProcedimento
inicio
    x <- 6
    y <- 4
    soma (x,y)
      Escreval ("O valor de x: ", x)
      Escreval ("O valor de y: ", y)
    
fimalgoritmo